### ISSUE TITLE
winmapgis wasn't detected

### ISSUE THREAD

**Issue by Mayssa1000** [stgeorges/gismo#13]
1. The folder path you added to Gismo_Gismo component's "mapFolder_" input is invalid: meaning this is not the MapWinGIS application install folder.
-
You can find the valid "mapFolder_" path by using the Start Menu -> Search function (and search for "MapWinGIS").
If you do not input the correct folder path to "mapWindow" some Gismo components might not be able to work.

**Comment by stgeorges** [comment]
Hi @Mayssa1000 ,
This message happens when ```Gismo Gismo``` component is not able to find the ```Interop.MapWinGIS.dll``` file after installation of MapWinGIS.
Try searching your PC for this file.
1. If you find it, then input that folder where the file is located into the ```mapFolder_``` of the ```Gismo Gismo``` component.
2. If you didn't find it, then it means that MapWinGIS installation was not successful. Probably you installed MapWinGIS by not unblocking the ```MapWinGIS-only-v4.9.6.1-x64.exe``` file when you downloaded it to your PC. In that case, you have to reinstall MapWinGIS with some custom uninstallation software (Windows default uninstaller, will leave plenty of leftovers). For example reinstall it with free version of Revo Uninstaller. Then install MapWinGIS again, but make sure the ```MapWinGIS-only-v4.9.6.1-x64.exe``` is unblocked (right click on it, and check "Unblock").

**Comment by Mayssa1000** [comment]
thank you for the answer, effectivement it works, but i have another problem , i started your plugin with the exemple of create building and streets and trees, but when i change the latitude and longetude the canvas don't show any data, than k you

**Comment by stgeorges** [comment]
Hi @Mayssa1000 ,
Do you mind if I ask, how did you solve your ```winmapgis wasn't detected``` problem?

**Comment by Mayssa1000** [comment]
Hi!, 
1-instal mapgis 5...
2-copy 'Interop.MapWinGIS.dll' on my desktop
3-reinstall winmapgis
4-go to c;\gizmo and past 'Interop.MapWinGIS.dll' 
5-open grasshopper plug c;^gizmo and winmap to gizmo

Ps; Interop.MapWinGIS.dll put it inside gizmo in grasshopper folder

Cordialement

**Comment by stgeorges** [comment]
Hi @Mayssa1000 ,
Thank you for the steps.
MapWinGIS 5 is currently not supported.
You need to install this 4.9.6.1 version from:
https://github.com/stgeorges/gismo#requirements

**Comment by Mayssa1000** [comment]
but when i use it with the file (exemple) streets ... works fine
ok i will change to the version 4
thank you

**Comment by stgeorges** [comment]
I understood you have issues with specific latitude and longitude? Or now everything works?
When you install ```MapWinGIS-only-v4.9.6.1-x64.exe```, make sure to unblock the .exe file first (right click on it, and choose ```Unblock```).

**Comment by Mayssa1000** [comment]
unblock i always do this for my files of grasshopper, now nothing works, same error

**Comment by stgeorges** [comment]
Did you just use regular Windows uninstall?
You have to use some custom uninstaller, which removes the MapWinGIS registry files as well. I recommend free version of Revo Uninstaller:
https://www.revouninstaller.com/products/revo-uninstaller-free

**Comment by Mayssa1000** [comment]
this is the error
"            {0;0}
0. Runtime error (COMException): Bibliothèque non inscrite. (Exception de HRESULT : 0x8002801D (TYPE_E_LIBNOTREGISTERED))

Traceback:
  line 308, in mapWinGIS, "<string>"
  line 2973, in script
"

**Comment by Mayssa1000** [comment]
ok i will try it

**Comment by stgeorges** [comment]
You already uninstalled MapWinGIS 5 with Windows default uninstaller?
Then you can't use Free Revo Uninstaller. Free version has no capability to remove registry files from the already uninstalled application. I don't know which other free uninstaller you should use.
I am sorry, I can't help you. Following the steps in essential in order for Gismo installation to be successful.

**Comment by Mayssa1000** [comment]
befor starting the icon is red 
![image](https://github.com/stgeorges/gismo/assets/103060220/c71aaac1-c9b6-4700-9728-0e04636be4a8)

**Comment by stgeorges** [comment]
Which software did you use to cleanup the MapWinGIS 5 registry leftovers?

**Comment by Mayssa1000** [comment]
but the plugin works fine with version 5, it shows all data with the ex file (building, street, trees..)and the only problem was , the change of lat/long that's all

**Comment by Mayssa1000** [comment]
done with this
https://www.revouninstaller.com/products/revo-uninstaller-free/

**Comment by stgeorges** [comment]
@Mayssa1000 if you already uninstalled MapWinGIS 5 with Windows uninstaller, then you can't use Free version of Revo Uninstaller to clean its registry leftovers. Free version does not support this.

As for the version 5: I didn't have time to invest what works and what not.
So the support I offer is for the v4.9.6.1 version.

I am sorry, I can't help you further: following installation steps is essential for Gismo to work:
https://github.com/stgeorges/gismo#requirements

**Comment by Mayssa1000** [comment]
{0;0}
0. The following error has been raised:
 
System.Runtime.InteropServices.COMException (0x80040154): La récupération de la fabrique de classes COM pour le composant avec le CLSID {CE7E6869-6F74-4E9D-9F07-3DCBADAB6299} a échoué en raison de l'erreur suivante : 80040154 Classe non enregistrée (Exception de HRESULT : 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 
 
If upper error is:
1) "Retrieving the COM class factory for component with CLSID..." then try the following fix:
 a) Close Rhino. Restart your PC. Once the PC boots up, double click on the "regMapWinGIS.cmd" file in "MapWinGIS" installation folder. When it closes the Command Prompt window it opened, try running Rhino, Grasshopper and the component again.
 b) If the upper COM class error appears again, then close Rhino, and uninstall the MapWinGIS application. It is advisable to do that with an application which does that by removing not only the installation files but also the leftover files (like those from registry). For example, use the: Revo Uninstaller Pro. A free 30 days full working version can be downloaded from: http://www.revouninstaller.com.
 After the Revo Uninstaller Pro uninstalls MapWinGIS, install it again, but this time by running the installation file by right clicking on it, and choosing: Run as -> Administrator. After the installation is complete double click on "regMapWinGIS.cmd" file in "MapWinGIS" installation folder. When it closes the Command Prompt window it opened, try running Rhino, Grasshopper and the component again.
 If after this the COM class error appears again, then post a question about this issue at:
 http://www.grasshopper3d.com/group/gismo/forum.
 
 
2) If the upper error is not "Retrieving the COM class factory for component with CLSID...", please post a question about this issue at:
http://www.grasshopper3d.com/group/gismo/forum.

**Comment by Mayssa1000** [comment]
i will look at next time, thank you for help, next time, have nice day
